#!/bin/bash

# Install web server
apt-get update
apt-get -y install nginx

# Create a new Virtual Host configuration file
sudo nano /etc/nginx/sites-available/redirect.conf

cat <<EOF | sudo tee /etc/apache2/sites-available/redirect.conf
<VirtualHost *:80>
    ServerName ayocoding12.tech
    Redirect 301 / http://ayocoding12.tech
</VirtualHost>
EOF

# Enable the Virtual Host
sudo a2ensite redirect.conf

# Reload Apache2 to apply the changes
sudo systemctl reload apache2
