#!/usr/bin/env bash

# Install Nginx
sudo apt-get update && sudo apt-get -y install nginx

# Create web page files
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www/html
echo 'Hello World!' | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure Nginx
sudo sed -i 's/^/# /g' /etc/nginx/sites-enabled/default # comment out default config
cat <<EOF | sudo tee /etc/nginx/sites-available/custom-header
server {
    listen 80;
    server_name _;
    add_header X-Served-By \$hostname;

    location = /404.html {
        root /var/www/html;
        internal;
    }

    location /redirect_me {
        return 301 https://www.blog.ehoneahobed.com;
    }
}
EOF
sudo ln -s /etc/nginx/sites-available/custom-header /etc/nginx/sites-enabled/custom-header # enable custom config

# Allow requests through port 80
sudo ufw allow 'Nginx HTTP'

# Restart Nginx
sudo systemctl restart nginx
