#!/usr/bin/env bash

# Update the package repository and install Nginx
sudo apt update
sudo apt install -y nginx

# Set up the index and error pages
sudo tee /var/www/html/index.html > /dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>
EOF

sudo tee /var/www/html/error.html > /dev/null <<EOF
<!DOCTYPE html>
<html>
<head>
    <title>Error 404</title>
</head>
<body>
    <h1>Error 404: Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF

# Set up the Nginx configuration file
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    error_page 404 /error.html;

    add_header X-Served-By \$hostname;

    location /error.html {
        internal;
    }

    location /redirect_me {
        return 301 https://www.google.com;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx
sudo systemctl restart nginx
