#!/usr/bin/env bash

# Debug Nginx port 80 by replacing the default configuration file in the enabled sites directory
# with a symbolic link to the default configuration file in the available sites directory.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service
sudo systemctl restart nginx.service
