#!/usr/bin/env bash

# Create a symbolic link to the default Nginx configuration file in the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

# Start the Nginx service
systemctl start nginx.service

# Get the process ID of the first Nginx process and kill it
kill "$(pgrep 'nginx' | head -n 1)"
